/**
 * Typed entry point over the WASM build of `rewood-core`.
 *
 * `pkg/` is generated by `pnpm build:wasm` (wasm-pack, node target) and is
 * not committed. Browser builds use `pkg-web/` from `pnpm build:wasm:web`.
 */
import * as wasm from '../pkg/rewood.js';
import type { Fix, FurnitureSpec, LibrariesSnapshot, ManufacturingPlan, PackageFile } from './types.js';

export * from './types.js';

/** Compile a spec into a manufacturing plan. Deterministic; never throws on bad input. */
export function compile(spec: FurnitureSpec): ManufacturingPlan {
  return JSON.parse(wasm.compile(JSON.stringify(spec))) as ManufacturingPlan;
}

/** Same as `compile`, for a spec you already hold as a JSON string. */
export function compileJson(specJson: string): ManufacturingPlan {
  return JSON.parse(wasm.compile(specJson)) as ManufacturingPlan;
}

/** The manufacturing package (DXF per part, CSVs, plan, manifest) as in-memory files. */
export function packageFiles(spec: FurnitureSpec): PackageFile[] {
  return JSON.parse(wasm.package_files(JSON.stringify(spec))) as PackageFile[];
}

export function applyFix(spec: FurnitureSpec, fix: Fix): FurnitureSpec {
  return JSON.parse(wasm.apply_fix(JSON.stringify(spec), JSON.stringify(fix))) as FurnitureSpec;
}

export function libraries(): LibrariesSnapshot {
  return JSON.parse(wasm.libraries()) as LibrariesSnapshot;
}

export function engineVersion(): string {
  return wasm.engine_version();
}

export function schemaVersion(): string {
  return wasm.schema_version();
}
